redditapp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
end

redditapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

redditapp/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
  primary_key: :id, 
  foreign_key: :moderator_id,
  class_name: :User
end

redditapp/app/models/user.rb
class User < ApplicationRecord 
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_many :subs, 
  primary_key: :id, 
  foreign_key: :moderator_id,
  class_name: :Sub 
  
  attr_reader :password 

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      return user 
    else
      return nil 
    end
  end

  def password=(password)
    @password = password 
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

end

redditapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user 
  end

  def logout!
    @current_user.reset_session_token!
    session[session_token] = nil
    redirect_to new_session_url
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

end

redditapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def new

  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid Credentials"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

redditapp/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id 
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to new_sub_url
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages 
      redirect_to sub_url(@sub)
    end
  end

  def index
    @subs = Sub.all 
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def destroy
    @sub = current_user.subs.find(params[:id])
    if @sub 
      @sub.destroy 
      redirect_to subs_url
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to sub_url(@sub)
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

redditapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

redditapp/app/helpers/application_helper.rb
module ApplicationHelper
end

redditapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

redditapp/app/helpers/subs_helper.rb
module SubsHelper
end

redditapp/app/helpers/users_helper.rb
module UsersHelper
end

redditapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>

    <% if logged_in? %>
        <%= current_user.username %>
        <form action="<%=session_url%>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="authenticity_token"
          value="<%=form_authenticity_token%>">
          <input type="submit" value="Sign out">
        </form>
    <% else %>
      <a href="<%=new_user_url%>">Sign up</a>
      <a href="<%=new_session_url%>">Sign in</a>
    <% end %>

    <%= yield %>
  </body>
</html>

redditapp/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%=subs_url(@sub)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" 
  value="<%=form_authenticity_token%>">

  <label>Title
    <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%=@sub.description%>">
  </label>

  <input type="submit" value="Add Sub">
</form>

redditapp/app/views/subs/index.html.erb
<h1>All Subs</h1>

<%@subs.each do |sub|%>
  <a href="<%=sub_url(sub)%>"><%=sub.title%></a>
  <br><br>
<%end%>

<br><br>

<a href="<%=new_sub_url%>">Add a Sub!</a>

redditapp/app/views/subs/new.html.erb
<h1>Add a new Sub!</h1>

<form action="<%=subs_url%>" method="POST">
  <input type="hidden" name="authenticity_token" 
  value="<%=form_authenticity_token%>">

  <label>Title
    <input type="text" name="sub[title]">
  </label>

  <label>Description
    <input type="text" name="sub[description]">
  </label>

  <input type="submit" value="Add Sub">
</form>

redditapp/app/views/subs/show.html.erb
<h1><%=@sub.title%></h1>
<h2><%=@sub.description%></h2>


<form action="<%=subs_url(@sub)%>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" 
  value="<%=form_authenticity_token%>">

  <input type="submit" value="Delete Sub">
</form>

<br><br>

<a href="<%=edit_sub_url%>">Edit Sub</a>

<br><br>

<a href="<%=subs_url%>">Back to all Subs</a>

redditapp/app/views/users/new.html.erb
<h2>Sign up</h2>

<form action="<%=users_url%>" method="POST">
  <input type="hidden" name="authenticity_token" 
  value="<%=form_authenticity_token%>">

  <label>Username
    <input type="text" name="user[username]">
  </label>

  <label>Password
    <input type="text" name="user[password]">
  </label>

  <input type="submit" value="SIGN UP">

</form>